### ISSUE TITLE
CMake error on OSX

### ISSUE THREAD

**Issue by ZelimDamian** [floooh/oryol-test-app#1] opened 2016-10-20 21:40 UTC
To replicate:

```
git clone git@github.com:floooh/oryol-test-app.git
cd oryol-test-app
./fips gen
```

Then open `CMakeFile.txt` in CLion 1.2

Errors:

```
Error:The binary directory
  /Users/zelim/Library/Caches/CLion12/cmake/generated/b418702b/b418702b/__default__0/oryol_Core
is already used to build a source directory.  It cannot be used to build source directory
  /Users/zelim/code/cpp/fips/oryol/code/Modules/Core
Specify a unique binary directory name.
```

**Comment by floooh** [comment] 2016-10-21 14:22
Hello, I haven't looked into CLion for a while. I'm not sure what's going on, need to investigate this. It will be a few days though since I currently only have very slow internet and don't have CLion installed.

Cheers,
-Floh.

**Comment by floooh** [comment] 2016-10-26 19:32
This is a bit more complex, the problem seems to be the import mechanism I'm using in fips. I can reproduce the problem by running cmake manually for oryol-test-app (everything works when building Oryol itself). 

I'm closing this bug and have opened a new bug in fips: https://github.com/floooh/fips/issues/134

**Closed as completed by floooh** 2016-10-26 19:32 UTC
